// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAVbxFHEALroSEtnCOWVlH-Dch24TuAup8',
    appId: '1:314865894708:web:5ca5ef646e915cc3279161',
    messagingSenderId: '314865894708',
    projectId: 'e-barber-4d52a',
    authDomain: 'e-barber-4d52a.firebaseapp.com',
    storageBucket: 'e-barber-4d52a.appspot.com',
    measurementId: 'G-WQ8FQQ8MXF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCwDlHn2MIGzWNmwomF9PTqSyWXThEheoI',
    appId: '1:314865894708:android:00a8fd54b99bf329279161',
    messagingSenderId: '314865894708',
    projectId: 'e-barber-4d52a',
    storageBucket: 'e-barber-4d52a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD-wuV40g-ZmKxkDw9sUTkG-LL9O2cVO8U',
    appId: '1:314865894708:ios:fbeb98accaf62510279161',
    messagingSenderId: '314865894708',
    projectId: 'e-barber-4d52a',
    storageBucket: 'e-barber-4d52a.appspot.com',
    androidClientId: '314865894708-2rr1unshuku1o8uqgmn4jv6g5vlphriv.apps.googleusercontent.com',
    iosClientId: '314865894708-nju3p4h7t7p0udo09iu5mue8sfn6cin7.apps.googleusercontent.com',
    iosBundleId: 'com.example.eBarberV2',
  );
}
